### PR TITLE
doc: add document about how customize a entityCollection level property

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## Purpose

Add documentation about how to customize a `EntityCollection` level property.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by JiaLiPassion** [comment]
@wardbell, please review the document, thank you.

And you can see in step 2, in the doc, I only overwrite the `queryManySuccess` method of `AdditionalEntityCollectionReducerMethods`, but in some case, we may have to overwrite every methods of `EntityCollectionReducerMethods`, so I have a proposal to add a new `ActionPayload2EntityCollectionFactory`, this factory will save the data from `action.payload` to `EntityCollection instance`. By default, the properties such as `loading/changeState/loaded` will be set, but user can customize their own factory to save additional properties.

**Comment by SerkanSipahi** [comment]
@JiaLiPassion hi, angular-ngrx-data is now part of ngrx => https://next.ngrx.io/guide/data#ngrxdata :)

**Comment by JiaLiPassion** [comment]
@SerkanSipahi, thanks! I will create PR there.

**Comment by johnpapa** [comment]
closing as this project is now merged with ngrx

**Pull request closed without merging**
